### ISSUE TITLE
Cloning Repository Failed Due to Authentication

### ISSUE THREAD

**Issue by Diane-Best** [networkgeometry/directed-geometric-networks#1]
Hello authors,

I am experiencing difficulties cloning the repository '[directedS1](https://github.com/directed-geometric-networks/directedS1)'. When I attempt to clone using the HTTPS URL, I encounter the following error message:

remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/directed-geometric-networks/directedS1.git/'

Could you please provide guidance on how to resolve this issue? If there are specific steps I need to follow or settings I need to configure, kindly let me know.

Thank you for your assistance. I look forward to a prompt resolution.

Best regards,
Diane

**Comment by antoineallard** [comment]
Hi Diane,

Just to make sure, are you using the correct address for the repository? It should be `https://github.com/networkgeometry/directed-geometric-networks.git`.

I ask simply because the address appearing in your error message, `https://github.com/directed-geometric-networks/directedS1.git/`, does not exist, so perhaps this is why Github returns an authentification error.

Let me know.

**Comment by Diane-Best** [comment]
Thanks. The new URL works! Maybe you could update the installation command in readme, where the address for the repository is: https://github.com/directed-geometric-networks/directedS1.git

**Comment by antoineallard** [comment]
Oh you're right. Thank you for bringing this mistake to me. It has been corrected!
